### ISSUE TITLE
support multiple progress bars

### ISSUE THREAD

**Issue by a8m** [a8m/pb#10]

**Comment by nabijaczleweli** [comment]
I have a mostly working implementation, does this look good?

[![asciicast](https://asciinema.org/a/4j22vmqr134le8alie1qwow1b.png)](https://asciinema.org/a/4j22vmqr134le8alie1qwow1b)

**Comment by nabijaczleweli** [comment]
I have a 100% working implementation, does this look good to you?
[![asciicast](https://asciinema.org/a/83456.png)](https://asciinema.org/a/83456)

**Comment by a8m** [comment]
closed via #32
