### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by LingMan** [a8m/pb#113]
@a8m, could you please push a new release to crates.io? Would be good to be able to depend on https://github.com/a8m/pb/pull/100 and https://github.com/a8m/pb/pull/106.

**Comment by tyshko5** [comment]
@a8m @LingMan @sfackler is there going to be a new release? `cargo audit` complains since there were no releases for almost 2 years

**Comment by LingMan** [comment]
No need to ping me. If I could make a release, I wouldn't have needed to open an issue in the first place.

**Comment by a8m** [comment]
Thanks @LingMan and @tyshko5 for the reminder. Please, see https://crates.io/crates/pbr/1.1.0
