### ISSUE TITLE
weirdness when message has a newline character

### ISSUE THREAD

**Issue by mcginty** [a8m/pb#19]
I know this is kind of an edge case, but I noticed when I accidentally used a message string that had a newline character in it. `pb` doesn't deal with this case (either by stripping newlines or by drawing the progress bar differently), so it just spews out progress bar lines.

**Comment by a8m** [comment]
Thanks for reporting the issue @mcginty. do you have any suggestions how to deal with this?

**Comment by mcginty** [comment]
Don't know that there's particularly a right solution, but the quickest solution that still supports newlines would probably be, instead of just clearing and redrawing the current line (in pseudocode), repeating that clearing step and moving the cursor up for each newline counted in the message string.

**Comment by mcginty** [comment]
Or just convert all newlines to spaces 😛
