### ISSUE TITLE
support a max refresh rate

### ISSUE THREAD

**Issue by mcginty** [a8m/pb#21]
I'm using `pb` in a program that rapidy updates, but not cause too much excess resource usage by writing to and flushing stdout more often than is necessary. While I can take care of that in code in my application, it seems like something that'd be nice for `pb` to support in general.

Great library, by the way, and don't worry if I find time I'll start submitting PRs for these :).

**Comment by a8m** [comment]
Yeah, I have plans to add support for update the progress bar every x time.
for example:
```rust
bar.set_refresh_rate(Duration::seconds(1))
```

**Comment by mcginty** [comment]
That would be awesome. Thanks again - I just moved to using this in https://github.com/mcginty/shoop :) saved me a lot of time and complexity.
