### ISSUE TITLE
Update official documentation

### ISSUE THREAD

**Issue by nabijaczleweli** [a8m/pb#24]
~~Currently I can't seem to find a way to make `ProgressBar` print to a generic `std::io::Write`, which would be really helpful for generic code.~~

~~That would also require the ability to set `ProgressBar`'s width manually.~~

I couldn't find the aforementioned feature because the official docs are outdated.

**Comment by a8m** [comment]
Done; thanks @nabijaczleweli

**Comment by nabijaczleweli** [comment]
:+1:
