### ISSUE TITLE
Allow dynamically adding and removing bars from MultiBar

### ISSUE THREAD

**Issue by SirVer** [a8m/pb#35]
Thanks for this useful crate. 

I have one problem: My progress report keeps changing while I work on it. Specifically, I split some data into geometrically separated chunks - and this might recurse. I would love to add new progress bar and removes those that are done while my process runs. Is that a planned feature?

**Comment by a8m** [comment]
Hey @SirVer 
Thanks for your feedback and sorry about the delay.
I'm planning to add these functionalities. I believe it will be added in the next few weeks.

**Comment by feuerste** [comment]
Hej @a8m 
Did you add this functionality? If so, can you please provide an example?
Thanks a lot for your help!

**Comment by mmstick** [comment]
I've implemented this functionality in a fork. I will create a PR after I create an example to demonstrate it.
