### ISSUE TITLE
Canno't specify good type of ProgressBar

### ISSUE THREAD

**Issue by k0pernicus** [a8m/pb#39]
Hi,
I want to specify the type of a ProgressBar, created using `create_bar` from `MultiBar`, as a parameter of a function.
Unfortunately, I can't because: `module 'multi' is private`.

My specification is here:
```
fn my_function(nb: ProgressBar<pbr::multi::Pipe>) {
...
}
```

How can I specify this type please?

Thanks a lot!

**Comment by a8m** [comment]
Hi @k0pernicus 
Thanks for your comment.

This is really an issue, but it can be solved by exposing [`Pipe`](https://github.com/a8m/pb/blob/master/src/multi.rs#L218) in [`lib.rs`](https://github.com/a8m/pb/blob/master/src/lib.rs#L120).
Wanna do a quick PR ? :)

**Comment by k0pernicus** [comment]
Done! :-)

Thanks a lot!

**Comment by a8m** [comment]
I'll try to publish a new version tomorrow morning. 😃

**Comment by k0pernicus** [comment]
Nice, thanks :-)
