### ISSUE TITLE
No real time stdout sharing a MultiBar type

### ISSUE THREAD

**Issue by k0pernicus** [a8m/pb#41]
I declare a `MultiBar` type in `main()`

```
fn main() {
    ...
    let mut mb = MultiBar::on(stdout());
    mb.println("Your Application Header:");
    mb.println("");
    ...
    let chunks = webfile.download_chunks(&mut mb);
    ...
    mb.listen();
}
```

This is my code in `download_chunks`:

```
pub fn download_chunks(&self, mb: &mut MultiBar<Stdout>) -> Vec<Chunk> {

    let thread_childs = (0..self.authorized_threads).map(|current_chunk| {
        ...
        let mut nb = mb.create_bar(self.chunk_length);
        nb.tick_format("▏▎▍▌▋▊▉██▉▊▋▌▍▎▏");
        nb.show_message = true;
        nb.message(&format!("Downloading part {}: ", current_chunk));

        thread::spawn(move || {
            ...
            while let Ok(n) = body.read(&mut chunk_part) {
                if n == 0 {
                    nb.finish_println(&format!("Part {}: Pull complete", current_chunk));
                    break;
                }
                nb.message(&format!("Downloading part {}: ", current_chunk));
                nb.add(n as u64);
                body_content.extend_from_slice(&chunk_part[..n]);
            }
            ...
        })
    });
}
```

The problem is I don't have any real time update of `nb` during the execution of my program - just a standard output of some `Part X: Pull complete` when the program ending :-/

Is there any mistake in my code?

**Comment by k0pernicus** [comment]
No idea please? :-/

**Comment by dzobbe** [comment]
Hi,

I encountered a similar issue. I think in your case the problem come from the mb.listen() call. I don't know what is the logic of your code, may be the mb.listen does not update. Try to spawn a thread only for the mb.listen into your download_chunk function? Something like:

`...
let mut nb = mb.create_bar(self.chunk_length);
nb.tick_format("▏▎▍▌▋▊▉██▉▊▋▌▍▎▏");
nb.show_message = true;
nb.message(&format!("Downloading part {}: ", current_chunk));
thread::spawn(move || {mb.listen();});
...`
