### ISSUE TITLE
Please add an API for logging messages

### ISSUE THREAD

**Issue by kinnison** [a8m/pb#42]
Hi,

I'd love to use pb in my project, but I need to be able to log messages to the console which are not to be overwritten by the progress bars.  I happen to use python-ttystatus in my python projects and that has a method which takes a string, undraws the widgets, writes the string to the terminal, and then redraws the widgets.

This allows for the following sort of output...

```text
Generated Bananas OK
Made some cheese OK
Attempted to grill cheese FAIL
3 / 12 [=======>--------------------------------------------------------------]  25%
```

Where the messages can be added to at each stage.

I hope this sounds as useful to you as I would find it :-)

Thanks,

Daniel.

**Comment by steveatinfincia** [comment]
I've got a [fork that does the logging part](https://github.com/infincia/pb/tree/logging), both for ProgressBar and MultiBar. It doesn't allow appending to the end of an existing log message at the moment, just passes the messages through on each draw.

But I'm not sure whether that is the best way to add logging, let me know if I missed something that should have been obvious :D 

I'm also not sure whether it should allow formatting/colors somehow, or keep the number of lines on-screen below a specific limit (to create a virtual "log window", or what the final API should look like.
