### ISSUE TITLE
No final redraw when max_refresh_rate is set

### ISSUE THREAD

**Issue by mitsuhiko** [a8m/pb#45]
Currently if you have a max refresh rate set it's possible that the bar is not rendered at 100% when it finishes. This is particularly noticable with progress bars that tick a lot but only have few steps (like 5 in total).

**Comment by a8m** [comment]
Thanks for letting me know that.
I'm planing to handle it this weekend. but of course, PR is always welcomed 😃

**Comment by a8m** [comment]
Hi @mitsuhiko, sorry for the delay. 
Can you share with me some code that simulate this behavior? thanks.

**Comment by mitsuhiko** [comment]
I don't have a repro case right now but I think you should be easily able to repro it by making a progress bar with 5 steps and call tick a few thousand times per step rapidly. Like 10000 ticks one step, 10000 ticks one step, etc. until the bar is filled to 5.

Then run the program a few times and eventually you should see that one of the progress bars is not drawn to 100%.

**Comment by a8m** [comment]
I got it. I'm working on fixing that.
It's worth to mention that you can solve that now by calling [`finish`](http://a8m.github.io/pb/doc/pbr/struct.ProgressBar.html#method.finish) at the end of the work.

**Comment by feuerste** [comment]
Unfortunately a simple `finish` at the end doesn't help. The only reliable workaround I found to force a redraw at the end is calling
```rust
progress_bar.finish();
progress_bar.set_max_refresh_rate(None);
progress_bar.tick();
```

**Comment by a8m** [comment]
Hey @mitsuhiko, #53 was landed and a new version was publish.
Please open this issue, if you still have troubles. 

Thanks
