### ISSUE TITLE
Next crates.io release for FreeBSD fix

### ISSUE THREAD

**Issue by kcking** [a8m/pb#64]
Happy to see a fix for FreeBSD merged! When do you expect to release this to crates.io?

Thanks!

**Comment by kcking** [comment]
@sfackler I noticed you are also an owner on crates.io, we'd greatly appreciate a release to un-block our FreeBSD compatibility progress.

**Comment by a8m** [comment]
Hey, Thanks for opening this issue, and sorry for the delay.
I've published a new version.
