### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by winstonewert** [a8m/pb#84]
Hi,

There doesn't seem to be action on the pull requests/issues recently.

Would you like some help running this project?

**Comment by a8m** [comment]
Hey @winstonewert,
Yes. I would be happy to get some help with issue and PR reviews.
 
Thanks

**Comment by winstonewert** [comment]
Ok, what would help look like?

I was thinking of just forking the project, since lack of replies since July made me think you had just abandoned the project. So, if you'd just like me to take over the whole project I'm good with that.

On the other hand, it is your project and I don't want to step on any toes, and I'm just some random guy on the internet, so I understand you might not want to do that. If you'd like to me just go around offering opinions on all the issues/pull requests I can do that to, but I'd have to insist in that scenario that we actually do make decisions and close all the issues/pull requests on way or the other.

**Comment by a8m** [comment]
The project wasn't abandoned. However, my wife and I just had a baby a few months ago, so as you can imagine my time was pretty limited lately.

I'd be happy to get help especially with reviewing PRs and replying to issues. I've created a [gitter room](https://gitter.im/a8m/pb), so we can talk there as well. 


Closing, feel free to open if needed.
